# Generated by Django 5.2.5 on 2026-04-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee_training_attendance_performance_and_more'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='DashboardTraining',
        ),
        migrations.AlterField(
            model_name='employee',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training'),
        ),
    ]
