# Generated by Django 5.2.5 on 2026-04-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_training_dashboardtraining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.DeleteModel(
            name='DashboardTraining',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='training',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
