# Generated by Django 5.2.5 on 2026-04-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_adminnotification'),
        ('trainer', '0002_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='smart.trainingprogram'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainee')),
            ],
        ),
    ]
