# Generated by Django 5.2.5 on 2026-04-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_content_course_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='link',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('image', 'Image')], max_length=20),
        ),
    ]
