# Generated by Django 5.2.5 on 2026-04-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_adminnotification'),
        ('trainer', '0004_remove_content_link_remove_content_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.trainingprogram'),
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.trainingprogram'),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AlterField(
            model_name='progress',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_progress', to='smart.trainingprogram'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Trainee',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
