# Generated by Django 5.2.5 on 2026-04-30 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_adminnotification'),
        ('trainer', '0006_session_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.trainingprogram'),
        ),
    ]
