# Generated by Django 5.2.5 on 2026-04-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_remove_attendance_trainee_remove_course_trainer_and_more'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Training',
        ),
    ]
