# Generated by Django 5.2.5 on 2026-05-02 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_adminnotification'),
        ('trainee', '0004_answer_file_alter_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='smart.trainingprogram'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
