# Generated by Django 5.2.5 on 2026-04-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='accent_color',
        ),
    ]
