# Generated by Django 5.2.5 on 2026-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('Superadmin', 'Superadmin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Trainer', 'Trainer'), ('Trainee', 'Trainee')], max_length=20, null=True),
        ),
    ]
