# Generated by Django 5.2.5 on 2026-04-24 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_report_attendance_teamskillassessment_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
