# Generated by Django 5.2.5 on 2026-04-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_training_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RemoveField(
            model_name='teamskillassessment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='training',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='TeamSkillAssessment',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
