# Generated by Django 5.2.5 on 2026-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_report_remove_notification_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
