# Generated by Django 5.2.5 on 2026-04-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='TrainingManager',
        ),
    ]
