# Generated by Django 5.2.5 on 2026-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Trainer', 'Trainer'), ('Trainee', 'Trainee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
    ]
