# Generated by Django 5.2.5 on 2026-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noti',
            name='role',
        ),
        migrations.RemoveField(
            model_name='noti',
            name='type',
        ),
        migrations.AddField(
            model_name='noti',
            name='notification_type',
            field=models.CharField(default='info', max_length=20),
        ),
    ]
