# Generated by Django 5.2.5 on 2026-04-25 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_noti_role_remove_noti_type_and_more'),
        ('smart', '0002_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart.trainingprogram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Present', max_length=10),
        ),
    ]
