# Generated by Django 5.2.5 on 2026-04-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_attendance_training_alter_attendance_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
